Books routes
wolox-training/mm-rails pull request #8
Opened 2019-05-16 17:57 UTC by mnmallea

## Summary
- Implemented index route for Books.
- Implemented show route for Books.
- Both routes requires an authenticated user.
- Index route allows to search books by author, genre or title.

## Trello card
[Link](https://trello.com/c/cquuRpQI/21-crear-rutas-index-y-show-para-book)

2019-05-16 20:52 UTC, leoncalermo requested changes

2019-05-16 20:52 UTC, leoncalermo commented on app/serializers/book_preview_serializer.rb
> +  attribute(:image) do
instead this i would use this
```
def image
  { url: object.image } 
end
```
and in attributes above i would add the `:image` at the end of the line

2019-05-16 20:52 UTC, leoncalermo commented on app/serializers/actual_rent_serializer.rb
> +  attribute :starting_date, key: :from
instead this i would use this
```
def from
  object.starting_date
end
```
and add `:from` in the above attributes line

2019-05-16 20:52 UTC, leoncalermo commented on app/serializers/actual_rent_serializer.rb
> +  attribute :ending_date, key: :to
same

2019-05-16 20:52 UTC, leoncalermo commented on app/serializers/book_serializer.rb
> +  attribute :image, key: :image_url
same

2019-05-16 20:52 UTC, leoncalermo commented on app/controllers/books_controller.rb
> +    @book ||= Book.find params[:id]
we try to use the  parenthesis in the functions  for easy reading

2019-05-16 20:52 UTC, leoncalermo commented on app/controllers/books_controller.rb
> +    if book
we try to not use this way and even we try to not use else too hahah
in this case i would do something like this 
```
def show
  return render json: book if book.present?
  head :not_found
end
```

2019-05-16 20:52 UTC, leoncalermo commented on app/models/book.rb
> +    rents.find_by(':current_date between starting_date and ending_date',
this works?!? it's amazing 😍

2019-05-16 21:04 UTC, mnmallea commented on app/models/book.rb
> +    rents.find_by(':current_date between starting_date and ending_date',
yes :smile:

2019-05-17 18:16 UTC, leoncalermo approved these changes

2019-05-17 18:24 UTC, merged